version: "3.9"

services:
  nodecrud:
    image: nwetmonaye/nodecrud
    build: .
    ports:
      - "80:3000"
    environment:
      -DB_CONNECTION = mongodb+srv://nwetmon:EhyPQZCj6hFODwNj@cluster0.3anlxrd.mongodb.net/traingingdb?authMechanism=DEFAULT
      -DB_HOST=
